#!/usr/bin/env python3
"""Lightweight QA for StudyForge HTML rendered by Lesson Studio."""

from __future__ import annotations

import argparse
import re
from html.parser import HTMLParser
from pathlib import Path


class Parser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.stack: list[str] = []
        self.attrs_stack: list[dict[str, str]] = []
        self.visible_parts: list[str] = []
        self.textareas: list[dict[str, str]] = []
        self.current_textarea: dict[str, str] | None = None
        self.learner_tools_attrs: dict[str, str] | None = None
        self.ids: set[str] = set()
        self.details_open_with_solution: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr = {k: v or "" for k, v in attrs}
        self.stack.append(tag)
        self.attrs_stack.append(attr)
        if "id" in attr:
            self.ids.add(attr["id"])
        if attr.get("id") == "sfLearnerTools":
            self.learner_tools_attrs = attr
        if tag == "textarea":
            self.current_textarea = dict(attr)
            self.current_textarea["__text__"] = ""
        if tag == "details" and "open" in attr:
            self.details_open_with_solution.append("open-details")

    def handle_endtag(self, tag: str) -> None:
        if tag == "textarea" and self.current_textarea is not None:
            self.textareas.append(self.current_textarea)
            self.current_textarea = None
        if self.stack:
            self.stack.pop()
        if self.attrs_stack:
            self.attrs_stack.pop()

    def handle_data(self, data: str) -> None:
        if self.current_textarea is not None:
            self.current_textarea["__text__"] += data
            return
        if any(tag in {"script", "style"} for tag in self.stack):
            return
        self.visible_parts.append(data)


def validate(path: Path) -> list[str]:
    html = path.read_text(encoding="utf-8")
    parser = Parser()
    parser.feed(html)
    visible = " ".join(" ".join(parser.visible_parts).split())
    errors: list[str] = []

    required_ids = {
        "sfLearnerTools",
        "sfLearnerMenuToggle",
        "sfLearnerMenuPanel",
        "sfSaveStatus",
        "sfExportState",
        "sfImportState",
        "sfResetState",
    }
    missing = sorted(required_ids - parser.ids)
    if missing:
        errors.append("missing learner tools menu ids: " + ", ".join(missing))

    css = re.sub(r"/\*.*?\*/", "", html, flags=re.DOTALL)
    if re.search(r"\.sf-learner-(?:tools|menu)[^{]*{[^}]*position\s*:\s*(fixed|sticky|absolute)", css, re.I | re.S):
        errors.append("learner tools menu must not be fixed/sticky/absolute overlay")

    if re.search(r"Виртуальный\s+файл\s*:|Virtual\s+file\s*:", visible, re.I):
        errors.append("old virtual-file UI label is visible")

    if re.search(r"Правильный\s+ответ\s*:", visible, re.I):
        errors.append("correct answer is visible in initial UI")

    if re.search(r"bug\s+hunt|исправьте\s+код|найдите\s+и\s+исправьте|лабораторная", visible, re.I):
        has_code_textarea = any(
            "code" in (ta.get("class", "") + " " + ta.get("id", "") + " " + ta.get("data-sf-answer", "")).lower()
            and len(ta.get("__text__", "")) > 40
            for ta in parser.textareas
        )
        if not has_code_textarea:
            errors.append("lab appears to ask for code fixing but no editable code textarea was found")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate StudyForge HTML generated by Lesson Studio")
    parser.add_argument("html_file", type=Path)
    args = parser.parse_args()

    errors = validate(args.html_file)
    if errors:
        print(f"FAIL: {args.html_file}")
        for error in errors:
            print(f"- {error}")
        return 1
    print(f"PASS: {args.html_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
